apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
<<<<<<< Updated upstream
      - name: sample-app
        image: us-west1-docker.pkg.dev/qwiklabs-gcp-01-a7b30c338b9f/my-repository/sample-app:v2.0
=======
      - name: dev-container
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-01-a7b30c338b9f/my-repository/hello-cloudbuild:v1.0
>>>>>>> Stashed changes
        ports:
        - containerPort: 8080

